---

ospf:
  process_id: "1"
  router_id: "1.1.1.1"
  networks:
    - subnet: "10.1.2.0"
      intf: "g0/2"
      mask: "0.0.0.255"
      area: "0"
      cost: ""
      network_type: "point-to-point"
      authentication_type: ""
      authentication_key: ""
    - subnet: "1.1.1.1"
      intf: "loopback0"
      mask: "0.0.0.0"
      area: "0"
      cost: ""
      network_type: "point-to-point"
      authentication_type: ""
      authentication_key: ""
  passive_interfaces:
    - intf: "loopback0"